#!/bin/bash

set -e

if ! which inkscape > /dev/null 2>&1; then
    echo "Please install inkscape"
    exit 1
fi

for size in 100 200 500 1000; do
    for svg in namecoin-banner namecoin-coin namecoin-coin-transparent-letter; do
        inkscape --without-gui --export-png=png/${svg}_${size}px.png --export-width ${size} --export-background=black --export-background-opacity=0.0 svg/${svg}.svg
    done
done
